id: A0429E644
title: In Praise of Padmākara, the Great Guru of Uḍḍiyāna
type: translation
pechas:
- I2CB2CEA6
- I1886CCA1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:45:24.910028
  last_modified_at: 2023-01-04 11:45:24.910039
  collections:
  - Drikung Kyobpa Jikten Sumgön
  - Works of Tibetan Masters
alignment_to_base:
  I2CB2CEA6/8985: DD76
  I1886CCA1/2B7B: DD76
